### PR TITLE
Add useful search commands and explanations to intro page

### PR DESCRIPTION
**Pull request by Rot127**
Depends on https://github.com/rizinorg/book/pull/93

Adds a description about the most essential search methods.

This is not meant to be merged but merely here for feedback. If you like the style I can combine it with https://github.com/rizinorg/book/pull/79.

### CODE REVIEW

**Comment by wargio** [comment]
shouldn't this go to dev?

**Comment by Rot127** [comment]
Ah yes. It should.

**Comment by ret2libc** [comment]
by search methods you mean searching commands, don't you?

**Comment by Rot127** [comment]
Yes. But you are right. Those are not really search methods.

**Review by wargio — APPROVED** [review]

**Comment by XVilka** [comment]
Rebase, please

**Review by XVilka — APPROVED** [review]

**Review by ret2libc — APPROVED** [review]

**Review by wargio — APPROVED** [review]

**Pull request merged**
