### PR TITLE
Updated information about heap

### PR DESCRIPTION
**Pull request by PulakIIIT**
Updated information about the heap page considering all the changes done in the past few months. Should I add some more examples of the heap commands or it is better to keep it concise?

### CODE REVIEW

**Comment by wargio** [comment]
i think is ok. these changes are not yet in a release, right?

**Comment by PulakIIIT** [comment]
@wargio Yeah the changes are in `dev` branch, my bad

**Comment by wargio** [comment]
np

**Review by wargio — APPROVED** [review]
I think these changes a re good, let's wait for the others.

**Review by XVilka — APPROVED** [review]

**Pull request merged**
